# Generated by Django 4.2.28 on 2026-02-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compilation Error'), ('internal_error', 'Internal Error')], default='pending', max_length=20)),
                ('judge0_token', models.CharField(blank=True, max_length=100)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('compile_output', models.TextField(blank=True)),
                ('time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
